### ISSUE TITLE
Warning: separate entrypoint breaks CI pipelines

### ISSUE THREAD

**Issue by MatteoJoliveau** [newtmitch/docker-sonar-scanner#30]
Hi, not an issue per se, but I wanted to raise a warning for those who (like myself) use this image for Docker-based pipelines like Gitlab CI.

Since the split of entrypoint and cmd pipelines fail because the underlying engine is (probably) running `bash -c $MYCOMMANDS` as a custom CMD.

Since now we have `sonar-scanner` as the entrypoint, I get errors like `ERROR: Unrecognized option: -c` because it's passing it to `sonar-scanner`.

The solution is to override the image entrypoint in the pipeline, for example by setting (Gitlab CI syntax):
```yaml
analysis:
  stage: analysis
  image:
    name: newtmitch/sonar-scanner:3.2-alpine
    entrypoint: ['']
  dependencies:
    - tests
  script:
    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectBaseDir=.
```

I hope it can be useful to others.
Thanks for the image, btw!
